---

orgName: devops-lab

environments:
  dev:
    region: eastus2
    servicePrinciple: devops-lab-jenkins-dev
    resourceGroup: devops-lab-dev-rg
    adminUserKey: PLACEHOLDER ## fake value for demo purpose
  qa: 
    region: eastus
    servicePrinciple: devops-lab-jenkins-qa
    resourceGroup: devops-lab-qa-rg
    adminUserKey: /subscriptions/b7135393-f28b-4a35-b97a-6b68abbd309e/resourceGroups/myResourceGroup/providers/Microsoft.KeyVault/vaults/myvault-3721
  prod: 
    region: centralus
    servicePrinciple: devops-lab-jenkins-prod
    resourceGroup: devops-lab-prod-rg
    adminUserKey: PLACEHOLDER ## fake value for demo purpose

templates:
  azure-vm-python3:
    arm: azure-vm.json
    param: azure-vm.parameters.json
    script: python3.sh
    default:
      someVar: someValue ## fake value for demo purpose
  azure-ase-python: 
    arm: azure-ase-python.json ## fake value for demo purpose
    param: azure-ase-python.parameters.json ## fake value for demo purpose
    script: python-ase.sh ## fake value for demo purpose
    default:
      someVar: someValue ## fake value for demo purpose

artifactTypes:
  python:
    index-url: http://nexus:8081/repository/pypi-central/simple
    extra-index-url: http://nexus:8081/repository/pypi/simple
    trusted-host: nexus
